# Generated by Django 2.2.28 on 2024-01-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время запроса')),
                ('currency_name', models.CharField(help_text='Полное название валюты 1 (например, "Доллар США")', max_length=200, verbose_name='Название валюты 1')),
                ('currency_code', models.CharField(help_text='Международный код валюты 1 в соответствии с ISO 4217 (Общепринятый стандарт)', max_length=3, verbose_name='Код валюты 1')),
                ('target_currency', models.CharField(help_text='Полное название валюты 2 (например, "Российский рубль")', max_length=200, verbose_name='Название валюты 2')),
                ('target_currency_code', models.CharField(help_text='Международный код целевой валюты в соответствии с ISO 4217 (Общепринятый стандарт)', max_length=3, verbose_name='Код валюты 2')),
                ('rate', models.FloatField(verbose_name='Курс Валюта1/Валюта2')),
                ('reversed_rate', models.FloatField(verbose_name='Курс Валюта2/Валюта1')),
            ],
            options={
                'verbose_name': 'Запрос курса валюты',
                'verbose_name_plural': 'Запрос курса валюты',
                'ordering': ('-request_date',),
            },
        ),
    ]
