# Generated by Django 2.2.28 on 2024-01-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raterequest',
            options={'ordering': ('-request_date',), 'verbose_name': 'Запрос курса валюты', 'verbose_name_plural': 'Запросы курсов валют'},
        ),
    ]
