# Generated by Django 2.2.28 on 2024-01-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_request', '0002_auto_20240123_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raterequest',
            name='reversed_rate',
        ),
    ]
