# Generated by Django 2.2.28 on 2024-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_request', '0003_remove_raterequest_reversed_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raterequest',
            name='rate',
            field=models.FloatField(verbose_name='Курс'),
        ),
    ]
