# Generated by Django 2.2.28 on 2024-01-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_request', '0004_auto_20240123_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raterequest',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='raterequest',
            name='target_currency',
        ),
    ]
